# 1.Data Preparation

In [10]:
import pandas as pd
bids_df = pd.read_csv('.jupyter/bids_actual.csv')
train_df = pd.read_csv('.jupyter/train_actual.csv')
test_df = pd.read_csv('.jupyter/test_actual.csv')

# 2. Exploratory Data Analysis

In [11]:
print(train_df.shape)
print(test_df.shape)
print(bids_df.shape)

(2013, 4)
(4700, 3)
(7656334, 9)

In [12]:
bids_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7656334 entries, 0 to 7656333
Data columns (total 9 columns):
 #   Column       Dtype
---  ------       -----
 0   bid_id       int64
 1   bidder_id    object
 2   auction      object
 3   merchandise  object
 4   device       object
 5   time         int64
 6   country      object
 7   ip           object
 8   url          object
dtypes: int64(2), object(7)
memory usage: 525.7+ MB

In [13]:
train_df.head()

,bidder_id,payment_account,address,outcome
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0
1,624f258b49e77713fc34034560f93fb3hu3jo,a3d2de7675556553a5f08e4c88d2c228v1sga,ae87054e5a97a8f840a3991d12611fdcrfbq3,0.0
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,a3d2de7675556553a5f08e4c88d2c2280cybl,92520288b50f03907041887884ba49c0cl0pd,0.0
3,4bee9aba2abda51bf43d639013d6efe12iycd,51d80e233f7b6a7dfdee484a3c120f3b2ita8,4cb9717c8ad7e88a9a284989dd79b98dbevyi,0.0
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,a3d2de7675556553a5f08e4c88d2c22857ddh,2a96c3ce94b3be921e0296097b88b56a7x1ji,0.0

In [14]:
test_df.head()

,bidder_id,payment_account,address
0,49bb5a3c944b8fc337981cc7a9ccae41u31d7,a3d2de7675556553a5f08e4c88d2c228htx90,5d9fa1b71f992e7c7a106ce4b07a0a754le7c
1,a921612b85a1494456e74c09393ccb65ylp4y,a3d2de7675556553a5f08e4c88d2c228rs17i,a3d2de7675556553a5f08e4c88d2c228klidn
2,6b601e72a4d264dab9ace9d7b229b47479v6i,925381cce086b8cc9594eee1c77edf665zjpl,a3d2de7675556553a5f08e4c88d2c228aght0
3,eaf0ed0afc9689779417274b4791726cn5udi,a3d2de7675556553a5f08e4c88d2c228nclv5,b5714de1fd69d4a0d2e39d59e53fe9e15vwat
4,cdecd8d02ed8c6037e38042c7745f688mx5sf,a3d2de7675556553a5f08e4c88d2c228dtdkd,c3b363a3c3b838d58c85acf0fc9964cb4pnfa

In [15]:
bids_df.head()

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
0,0,8dac2b259fd1c6d1120e519fb1ac14fbqvax8,ewmzr,jewelry,phone0,9759243157894736,us,69.166.231.58,vasstdc27m7nks3
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c
2,2,aa5f360084278b35d746fa6af3a7a1a5ra3xe,wa00e,home goods,phone2,9759243157894736,py,112.54.208.157,vasstdc27m7nks3
3,3,3939ac3ef7d472a59a9c5f893dd3e39fh9ofi,jefix,jewelry,phone4,9759243157894736,in,18.99.175.133,vasstdc27m7nks3
4,4,8393c48eaf4b8fa96886edc7cf27b372dsibi,jefix,jewelry,phone5,9759243157894736,in,145.138.5.37,vasstdc27m7nks3

In [16]:
print(train_df.bidder_id.nunique())
print(test_df.bidder_id.nunique())
print(bids_df.bidder_id.nunique())

2013
4700
6614

In [17]:
train_bidder_ids = list(train_df.bidder_id)
test_bidder_ids = list(test_df.bidder_id)
bids_bidder_ids = list(bids_df.bidder_id.unique())

print(train_bidder_ids[:5])

['91a3c57b13234af24875c56fb7e2b2f4rb56a', '624f258b49e77713fc34034560f93fb3hu3jo', '1c5f4fc669099bfbfac515cd26997bd12ruaj', '4bee9aba2abda51bf43d639013d6efe12iycd', '4ab12bc61c82ddd9c2d65e60555808acqgos1']

In [18]:
##Check for no. unique bidder ids from train dataset not found in bids dataset
not_found = []
for bidderid in train_bidder_ids:
    if bidderid not in bids_bidder_ids:
        not_found.append(bidderid)
print(len(not_found), 'bidder ids from train_actual.csv are not found in bids_actual.csv')

29 bidder ids from train_actual.csv are not found in bids_actual.csv

In [19]:
##Check for no. unique bidder ids from test dataset not found in bids dataset
not_found = []
for bidderid in test_bidder_ids:
    if bidderid not in bids_bidder_ids:
        not_found.append(bidderid)
print(len(not_found), 'bidder ids from test_actual.csv are not found in bids_actual.csv')

70 bidder ids from test_actual.csv are not found in bids_actual.csv

In [20]:
##No. of unique data groups for each feature
bids_df.nunique()

bid_id         7656334
bidder_id         6614
auction          15051
merchandise         10
device            7351
time            776529
country            199
ip             2303991
url            1786351
dtype: int64

# 3. Feature Engineering

In [21]:
# max, avg bids grouped by auction, country, device, ip , url

max_avg_agg = pd.DataFrame()

max_avg_agg['max_bids_auc']=bids_df.groupby(['bidder_id', 'auction'])['bid_id'].count().max(level=0)
max_avg_agg[ 'avg_bids_auc']=bids_df.groupby(['bidder_id', 'auction'])['bid_id'].count().mean(level=0)

max_avg_agg['max_bids_dev']=bids_df.groupby(['bidder_id', 'device'])['bid_id'].count().max(level=0)
max_avg_agg[ 'avg_bids_dev']=bids_df.groupby(['bidder_id', 'device'])['bid_id'].count().mean(level=0)

max_avg_agg['max_bids_country']=bids_df.groupby(['bidder_id', 'country'])['bid_id'].count().max(level=0)
max_avg_agg[ 'avg_bids_country']=bids_df.groupby(['bidder_id', 'country'])['bid_id'].count().mean(level=0)

max_avg_agg['max_bids_ip']=bids_df.groupby(['bidder_id', 'ip'])['bid_id'].count().max(level=0)
max_avg_agg[ 'avg_bids_ip']=bids_df.groupby(['bidder_id', 'ip'])['bid_id'].count().mean(level=0)

max_avg_agg['max_bids_url']=bids_df.groupby(['bidder_id', 'url'])['bid_id'].count().max(level=0)
max_avg_agg[ 'avg_bids_url']=bids_df.groupby(['bidder_id', 'url'])['bid_id'].count().mean(level=0)

max_avg_agg = max_avg_agg.reset_index()
max_avg_agg

,bidder_id,max_bids_auc,avg_bids_auc,max_bids_dev,avg_bids_dev,max_bids_country,avg_bids_country,max_bids_ip,avg_bids_ip,max_bids_url,avg_bids_url
0,001068c415025a009fee375a12cff4fcnht8y,1,1.000000,1,1.000000,1.0,1.000000,1,1.000000,1,1.000000
1,002d229ffb247009810828f648afc2ef593rb,2,2.000000,1,1.000000,2.0,2.000000,2,2.000000,2,2.000000
2,0030a2dd87ad2733e0873062e4f83954mkj86,1,1.000000,1,1.000000,1.0,1.000000,1,1.000000,1,1.000000
3,003180b29c6a5f8f1d84a6b7b6f7be57tjj1o,1,1.000000,1,1.000000,3.0,3.000000,1,1.000000,2,1.500000
4,00486a11dff552c4bd7696265724ff81yeo9v,3,1.538462,7,2.500000,20.0,20.000000,6,2.000000,11,2.857143
...,...,...,...,...,...,...,...,...,...,...,...
6609,ffbc0fdfbf19a8a9116b68714138f2902cc13,3682,39.364207,2432,31.660354,18576.0,245.833333,159,1.339047,7031,3.119169
6610,ffc4e2dd2cc08249f299cab46ecbfacfobmr3,4,1.466667,4,1.692308,12.0,3.666667,2,1.222222,5,1.833333
6611,ffd29eb307a4c54610dd2d3d212bf3bagmmpl,1,1.000000,1,1.000000,1.0,1.000000,1,1.000000,1,1.000000
6612,ffd62646d600b759a985d45918bd6f0431vmz,78,12.072727,200,6.916667,664.0,664.000000,37,17.945946,436,4.611111
6613,fff2c070d8200e0a09150bd81452ce29ngcnv,1,1.000000,1,1.000000,1.0,1.000000,1,1.000000,1,1.000000

In [22]:
##sort the bids in ascending order of bidder_ids and time.

bids_sorted_df = bids_df.sort_values(['bidder_id', 'time'], ascending = [True, True])
bids_sorted_df.head()

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
7179832,7179832,001068c415025a009fee375a12cff4fcnht8y,4ifac,jewelry,phone561,9706345052631578,bn,139.226.147.115,vasstdc27m7nks3
1281292,1281292,002d229ffb247009810828f648afc2ef593rb,2tdw2,mobile,phone640,9766744105263157,sg,37.40.254.131,vasstdc27m7nks3
1281311,1281311,002d229ffb247009810828f648afc2ef593rb,2tdw2,mobile,phone219,9766744210526315,sg,37.40.254.131,vasstdc27m7nks3
6805028,6805028,0030a2dd87ad2733e0873062e4f83954mkj86,obbny,mobile,phone313,9704553947368421,ir,21.67.17.162,vnw40k8zzokijsv
3967330,3967330,003180b29c6a5f8f1d84a6b7b6f7be57tjj1o,obbny,mobile,phone420,9640018631578947,id,44.241.8.179,sj4jidex850loas

In [23]:
## compute the time differences between bids

timediff = bids_sorted_df.groupby('bidder_id')['time'].diff()
timediff= timediff.fillna('0')

bids_sorted_df['timediff'] = timediff
bids_sorted_df['timediff'] = bids_sorted_df['timediff'].astype(float)

bids_sorted_df.head()

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url,timediff
7179832,7179832,001068c415025a009fee375a12cff4fcnht8y,4ifac,jewelry,phone561,9706345052631578,bn,139.226.147.115,vasstdc27m7nks3,0.0
1281292,1281292,002d229ffb247009810828f648afc2ef593rb,2tdw2,mobile,phone640,9766744105263157,sg,37.40.254.131,vasstdc27m7nks3,0.0
1281311,1281311,002d229ffb247009810828f648afc2ef593rb,2tdw2,mobile,phone219,9766744210526315,sg,37.40.254.131,vasstdc27m7nks3,105263158.0
6805028,6805028,0030a2dd87ad2733e0873062e4f83954mkj86,obbny,mobile,phone313,9704553947368421,ir,21.67.17.162,vnw40k8zzokijsv,0.0
3967330,3967330,003180b29c6a5f8f1d84a6b7b6f7be57tjj1o,obbny,mobile,phone420,9640018631578947,id,44.241.8.179,sj4jidex850loas,0.0

In [24]:
time_agg = pd.DataFrame()

time_agg[['maxtime', 'mintime']] = bids_sorted_df.groupby('bidder_id')['time'].agg(['max','min'])
time_agg[['maxtimediff', 'meantimediff', 'mediantimediff']] = bids_sorted_df.groupby('bidder_id')['timediff'].agg(['max','mean','median'])
time_agg['duration']=time_agg['maxtime']-time_agg['mintime']
time_agg = time_agg.reset_index()
time_agg

,bidder_id,maxtime,mintime,maxtimediff,meantimediff,mediantimediff,duration
0,001068c415025a009fee375a12cff4fcnht8y,9706345052631578,9706345052631578,0.000000e+00,0.000000e+00,0.000000e+00,0
1,002d229ffb247009810828f648afc2ef593rb,9766744210526315,9766744105263157,1.052632e+08,5.263158e+07,5.263158e+07,105263158
2,0030a2dd87ad2733e0873062e4f83954mkj86,9704553947368421,9704553947368421,0.000000e+00,0.000000e+00,0.000000e+00,0
3,003180b29c6a5f8f1d84a6b7b6f7be57tjj1o,9705974315789473,9640018631578947,6.058642e+13,2.198523e+13,5.369263e+12,65955684210526
4,00486a11dff552c4bd7696265724ff81yeo9v,9708986368421052,9632636526315789,5.094174e+13,3.817492e+12,8.081316e+11,76349842105263
...,...,...,...,...,...,...,...
6609,ffbc0fdfbf19a8a9116b68714138f2902cc13,9772883842105263,9759243263157894,8.842105e+09,5.439912e+08,3.157895e+08,13640578947369
6610,ffc4e2dd2cc08249f299cab46ecbfacfobmr3,9708376684210526,9632853421052631,5.082974e+13,3.432876e+12,6.473947e+11,75523263157895
6611,ffd29eb307a4c54610dd2d3d212bf3bagmmpl,9642379947368421,9642379947368421,0.000000e+00,0.000000e+00,0.000000e+00,0
6612,ffd62646d600b759a985d45918bd6f0431vmz,9772881631578947,9759257315789473,2.590000e+11,2.051855e+10,1.094737e+10,13624315789474
6613,fff2c070d8200e0a09150bd81452ce29ngcnv,9705193473684210,9705193473684210,0.000000e+00,0.000000e+00,0.000000e+00,0

In [25]:
##Group features by no. of unique bidder ids
bidder_unique = bids_df.groupby("bidder_id").nunique()
bidder_unique

,bid_id,auction,merchandise,device,time,country,ip,url
bidder_id,,,,,,,,
001068c415025a009fee375a12cff4fcnht8y,1,1,1,1,1,1,1,1
002d229ffb247009810828f648afc2ef593rb,2,1,1,2,2,1,1,1
0030a2dd87ad2733e0873062e4f83954mkj86,1,1,1,1,1,1,1,1
003180b29c6a5f8f1d84a6b7b6f7be57tjj1o,3,3,1,3,3,1,3,2
00486a11dff552c4bd7696265724ff81yeo9v,20,13,1,8,20,1,10,7
...,...,...,...,...,...,...,...,...
ffbc0fdfbf19a8a9116b68714138f2902cc13,25075,637,1,792,23487,102,18726,8039
ffc4e2dd2cc08249f299cab46ecbfacfobmr3,22,15,1,13,22,6,18,12
ffd29eb307a4c54610dd2d3d212bf3bagmmpl,1,1,1,1,1,1,1,1
ffd62646d600b759a985d45918bd6f0431vmz,664,55,1,96,664,1,37,144
fff2c070d8200e0a09150bd81452ce29ngcnv,1,1,1,1,1,1,1,1

In [26]:
bidder_unique = bidder_unique.drop(columns='bidder_id', errors='ignore').reset_index()
bidder_unique

,bidder_id,bid_id,auction,merchandise,device,time,country,ip,url
0,001068c415025a009fee375a12cff4fcnht8y,1,1,1,1,1,1,1,1
1,002d229ffb247009810828f648afc2ef593rb,2,1,1,2,2,1,1,1
2,0030a2dd87ad2733e0873062e4f83954mkj86,1,1,1,1,1,1,1,1
3,003180b29c6a5f8f1d84a6b7b6f7be57tjj1o,3,3,1,3,3,1,3,2
4,00486a11dff552c4bd7696265724ff81yeo9v,20,13,1,8,20,1,10,7
...,...,...,...,...,...,...,...,...,...
6609,ffbc0fdfbf19a8a9116b68714138f2902cc13,25075,637,1,792,23487,102,18726,8039
6610,ffc4e2dd2cc08249f299cab46ecbfacfobmr3,22,15,1,13,22,6,18,12
6611,ffd29eb307a4c54610dd2d3d212bf3bagmmpl,1,1,1,1,1,1,1,1
6612,ffd62646d600b759a985d45918bd6f0431vmz,664,55,1,96,664,1,37,144
6613,fff2c070d8200e0a09150bd81452ce29ngcnv,1,1,1,1,1,1,1,1

In [27]:
##Merge unique bidder id table with max_avg table
bids_agg = bidder_unique.merge(max_avg_agg, on='bidder_id', how='left')
bids_agg

,bidder_id,bid_id,auction,merchandise,device,time,country,ip,url,max_bids_auc,avg_bids_auc,max_bids_dev,avg_bids_dev,max_bids_country,avg_bids_country,max_bids_ip,avg_bids_ip,max_bids_url,avg_bids_url
0,001068c415025a009fee375a12cff4fcnht8y,1,1,1,1,1,1,1,1,1,1.000000,1,1.000000,1.0,1.000000,1,1.000000,1,1.000000
1,002d229ffb247009810828f648afc2ef593rb,2,1,1,2,2,1,1,1,2,2.000000,1,1.000000,2.0,2.000000,2,2.000000,2,2.000000
2,0030a2dd87ad2733e0873062e4f83954mkj86,1,1,1,1,1,1,1,1,1,1.000000,1,1.000000,1.0,1.000000,1,1.000000,1,1.000000
3,003180b29c6a5f8f1d84a6b7b6f7be57tjj1o,3,3,1,3,3,1,3,2,1,1.000000,1,1.000000,3.0,3.000000,1,1.000000,2,1.500000
4,00486a11dff552c4bd7696265724ff81yeo9v,20,13,1,8,20,1,10,7,3,1.538462,7,2.500000,20.0,20.000000,6,2.000000,11,2.857143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6609,ffbc0fdfbf19a8a9116b68714138f2902cc13,25075,637,1,792,23487,102,18726,8039,3682,39.364207,2432,31.660354,18576.0,245.833333,159,1.339047,7031,3.119169
6610,ffc4e2dd2cc08249f299cab46ecbfacfobmr3,22,15,1,13,22,6,18,12,4,1.466667,4,1.692308,12.0,3.666667,2,1.222222,5,1.833333
6611,ffd29eb307a4c54610dd2d3d212bf3bagmmpl,1,1,1,1,1,1,1,1,1,1.000000,1,1.000000,1.0,1.000000,1,1.000000,1,1.000000
6612,ffd62646d600b759a985d45918bd6f0431vmz,664,55,1,96,664,1,37,144,78,12.072727,200,6.916667,664.0,664.000000,37,17.945946,436,4.611111
6613,fff2c070d8200e0a09150bd81452ce29ngcnv,1,1,1,1,1,1,1,1,1,1.000000,1,1.000000,1.0,1.000000,1,1.000000,1,1.000000

In [28]:
##Merge aggregated bids table with time difference table
bids_aggr = bids_agg.merge(time_agg, on='bidder_id', how='left')

bids_aggr['bids_per_auction']= bids_aggr['bid_id']/bids_aggr['auction']
bids_aggr['bids_per_device']= bids_aggr['bid_id']/bids_aggr['device']
bids_aggr['bids_per_country']= bids_aggr['bid_id']/bids_aggr['country']
bids_aggr['bids_per_ip']= bids_aggr['bid_id']/bids_aggr['ip']
bids_aggr['bids_per_url']= bids_aggr['bid_id']/bids_aggr['url']
bids_aggr

,bidder_id,bid_id,auction,merchandise,device,time,country,ip,url,max_bids_auc,...,mintime,maxtimediff,meantimediff,mediantimediff,duration,bids_per_auction,bids_per_device,bids_per_country,bids_per_ip,bids_per_url
0,001068c415025a009fee375a12cff4fcnht8y,1,1,1,1,1,1,1,1,1,...,9706345052631578,0.000000e+00,0.000000e+00,0.000000e+00,0,1.000000,1.000000,1.000000,1.000000,1.000000
1,002d229ffb247009810828f648afc2ef593rb,2,1,1,2,2,1,1,1,2,...,9766744105263157,1.052632e+08,5.263158e+07,5.263158e+07,105263158,2.000000,1.000000,2.000000,2.000000,2.000000
2,0030a2dd87ad2733e0873062e4f83954mkj86,1,1,1,1,1,1,1,1,1,...,9704553947368421,0.000000e+00,0.000000e+00,0.000000e+00,0,1.000000,1.000000,1.000000,1.000000,1.000000
3,003180b29c6a5f8f1d84a6b7b6f7be57tjj1o,3,3,1,3,3,1,3,2,1,...,9640018631578947,6.058642e+13,2.198523e+13,5.369263e+12,65955684210526,1.000000,1.000000,3.000000,1.000000,1.500000
4,00486a11dff552c4bd7696265724ff81yeo9v,20,13,1,8,20,1,10,7,3,...,9632636526315789,5.094174e+13,3.817492e+12,8.081316e+11,76349842105263,1.538462,2.500000,20.000000,2.000000,2.857143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6609,ffbc0fdfbf19a8a9116b68714138f2902cc13,25075,637,1,792,23487,102,18726,8039,3682,...,9759243263157894,8.842105e+09,5.439912e+08,3.157895e+08,13640578947369,39.364207,31.660354,245.833333,1.339047,3.119169
6610,ffc4e2dd2cc08249f299cab46ecbfacfobmr3,22,15,1,13,22,6,18,12,4,...,9632853421052631,5.082974e+13,3.432876e+12,6.473947e+11,75523263157895,1.466667,1.692308,3.666667,1.222222,1.833333
6611,ffd29eb307a4c54610dd2d3d212bf3bagmmpl,1,1,1,1,1,1,1,1,1,...,9642379947368421,0.000000e+00,0.000000e+00,0.000000e+00,0,1.000000,1.000000,1.000000,1.000000,1.000000
6612,ffd62646d600b759a985d45918bd6f0431vmz,664,55,1,96,664,1,37,144,78,...,9759257315789473,2.590000e+11,2.051855e+10,1.094737e+10,13624315789474,12.072727,6.916667,664.000000,17.945946,4.611111
6613,fff2c070d8200e0a09150bd81452ce29ngcnv,1,1,1,1,1,1,1,1,1,...,9705193473684210,0.000000e+00,0.000000e+00,0.000000e+00,0,1.000000,1.000000,1.000000,1.000000,1.000000

In [29]:
##Combine table of all aggregated features with train and test dataset
train_set = train_df.merge(bids_aggr, on='bidder_id', how='left')
test_set = test_df.merge(bids_aggr, on='bidder_id', how='left')

In [30]:
##Replace null values with 0s
train_set = train_set.fillna(0)
test_set = test_set.fillna(0)

In [31]:
test_set.isnull().sum()

bidder_id           0
payment_account     0
address             0
bid_id              0
auction             0
merchandise         0
device              0
time                0
country             0
ip                  0
url                 0
max_bids_auc        0
avg_bids_auc        0
max_bids_dev        0
avg_bids_dev        0
max_bids_country    0
avg_bids_country    0
max_bids_ip         0
avg_bids_ip         0
max_bids_url        0
avg_bids_url        0
maxtime             0
mintime             0
maxtimediff         0
meantimediff        0
mediantimediff      0
duration            0
bids_per_auction    0
bids_per_device     0
bids_per_country    0
bids_per_ip         0
bids_per_url        0
dtype: int64

In [32]:
train_set

,bidder_id,payment_account,address,outcome,bid_id,auction,merchandise,device,time,country,...,mintime,maxtimediff,meantimediff,mediantimediff,duration,bids_per_auction,bids_per_device,bids_per_country,bids_per_ip,bids_per_url
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0,24.0,18.0,1.0,14.0,24.0,6.0,...,9.759489e+15,3.167632e+12,5.473158e+11,3.147895e+11,1.313558e+13,1.333333,1.714286,4.0,1.200000,24.000000
1,624f258b49e77713fc34034560f93fb3hu3jo,a3d2de7675556553a5f08e4c88d2c228v1sga,ae87054e5a97a8f840a3991d12611fdcrfbq3,0.0,3.0,1.0,1.0,2.0,3.0,1.0,...,9.764047e+15,4.477842e+12,2.155719e+12,1.989316e+12,6.467158e+12,3.000000,1.500000,3.0,1.000000,1.500000
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,a3d2de7675556553a5f08e4c88d2c2280cybl,92520288b50f03907041887884ba49c0cl0pd,0.0,4.0,4.0,1.0,2.0,4.0,1.0,...,9.765400e+15,3.154105e+12,1.784250e+12,1.991447e+12,7.137000e+12,1.000000,2.000000,4.0,1.000000,2.000000
3,4bee9aba2abda51bf43d639013d6efe12iycd,51d80e233f7b6a7dfdee484a3c120f3b2ita8,4cb9717c8ad7e88a9a284989dd79b98dbevyi,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,9.706442e+15,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,1.000000,1.0,1.000000,1.000000
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,a3d2de7675556553a5f08e4c88d2c22857ddh,2a96c3ce94b3be921e0296097b88b56a7x1ji,0.0,155.0,23.0,1.0,53.0,155.0,2.0,...,9.759247e+15,1.619211e+12,7.727708e+10,1.363158e+10,1.197795e+13,6.739130,2.924528,77.5,1.260163,1.703297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008,369515b3af4f8ca582f90271d30b14b6r52aw,a1f85275793c4a782f0a668711f41b927ivc9,e6882cf204a9482edd042b6e31791dfctxzx8,0.0,36.0,25.0,1.0,4.0,33.0,4.0,...,9.633559e+15,5.605500e+13,2.040852e+12,6.578947e+08,7.347068e+13,1.440000,9.000000,9.0,7.200000,18.000000
2009,f939c17ffc7c39ac9b35b69e5e75179fv9pe2,a3d2de7675556553a5f08e4c88d2c2286s1m2,b9b03d5a127eb07aeb9163cdcf524e1344ac9,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,9.705152e+15,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,1.000000,1.0,1.000000,1.000000
2010,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,a3d2de7675556553a5f08e4c88d2c22856leq,d02c2b288b8aabd79ff47118aff41a2dqwzwc,0.0,2.0,1.0,1.0,2.0,2.0,1.0,...,9.762802e+15,9.798474e+12,4.899237e+12,4.899237e+12,9.798474e+12,2.000000,1.000000,2.0,1.000000,2.000000
2011,0381a69b7a061e9ace2798fd48f1f537mgq57,fd87037ce0304077079c749f420f0b4c54uo0,f030a221726fbcdfc4dc7dfd1b381a112hieq,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,9.636754e+15,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,1.000000,1.0,1.000000,1.000000
2012,84a769adc98498f52debfe57b93a0789556f4,fbe0ce34d6546ebd9e4c63afc68b085byd2tf,a3d2de7675556553a5f08e4c88d2c228fib6p,0.0,2.0,1.0,1.0,1.0,2.0,1.0,...,9.770756e+15,1.789474e+09,8.947368e+08,8.947368e+08,1.789474e+09,2.000000,2.000000,2.0,2.000000,2.000000

# 4. Model Training

In [33]:
##Selecting feature columns for model validation
feature_cols = ['bid_id','auction','merchandise','device','time','country','ip','url','max_bids_auc', 'avg_bids_auc',
                'max_bids_dev','avg_bids_dev','max_bids_country','avg_bids_country','max_bids_ip','avg_bids_ip',
                'max_bids_url','avg_bids_url','maxtime','mintime','maxtimediff','meantimediff','mediantimediff','duration',
     'bids_per_auction']

X = train_set[feature_cols]
y = train_set['outcome']

In [34]:
#install imbalance-learn library
!pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Requirement already satisfied: imbalanced-learn in c:\users\user\anaconda3\lib\site-packages (from imblearn) (0.8.1)
Requirement already satisfied: scikit-learn>=0.24 in c:\users\user\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (0.24.1)
Requirement already satisfied: scipy>=0.19.1 in c:\users\user\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.6.2)
Requirement already satisfied: numpy>=1.13.3 in c:\users\user\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.20.1)
Requirement already satisfied: joblib>=0.11 in c:\users\user\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn>=0.24->imbalanced-learn->imblearn) (2.1.0)
Installing collected packages: imblearn
Successfully installed imblearn-0.0

In [35]:
##Importing selected models and libraries
from imblearn.pipeline import Pipeline, make_pipeline
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn import metrics
import statistics

In [36]:
## manual oversampling in CV

In [37]:
#Model validation
from catboost import CatBoostClassifier
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')
#Ensemble model of RandomForest, Xgboost and catboost
rf_model = RandomForestClassifier(n_estimators=100, max_depth=4,random_state=0, max_features="log2")
cat_model = CatBoostClassifier(random_seed = 0, depth = 4,verbose=False) #default depth =6
xgb_model = xgb.XGBClassifier(random_state=0, max_depth=4)
    
kf = KFold(n_splits=10)
smoter = SMOTE(random_state=0)
    
k_fold_auc = []

    # Iterate through each fold and calculate the auc, accuracy for each fold
for train_index, test_index in kf.split(X, y):
        
        # Extract the training and test data
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        # Upsample only the data in the training section
        X_train_upsample, y_train_upsample = smoter.fit_resample(X_train,y_train)
        
        # Fit the model on the upsampled training data
        rf_model.fit(X_train_upsample, y_train_upsample)
        cat_model.fit(X_train_upsample, y_train_upsample)
        xgb_model.fit(X_train_upsample, y_train_upsample)
        
        y_pred1 = rf_model.predict(X_test)
        y_pred2 = cat_model.predict(X_test)
        y_pred3 = xgb_model.predict(X_test)
        
        #Calculate Accuracy, AUC for the fold and append it
        
        final_pred = (y_pred1 * 0.6) + (y_pred2 * 0.3) + (y_pred3 * 0.1)

        auc = metrics.roc_auc_score(y_test, final_pred)

        k_fold_auc.append(auc)

print('The average auc is:', statistics.mean(k_fold_auc))

[16:47:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:25] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:28] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:32] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:37] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:41] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:45] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:56] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
The average auc is: 0.8773339107012414

In [38]:
print(cat_model.get_all_params())

{'nan_mode': 'Min', 'eval_metric': 'Logloss', 'iterations': 1000, 'sampling_frequency': 'PerTree', 'leaf_estimation_method': 'Newton', 'grow_policy': 'SymmetricTree', 'penalties_coefficient': 1, 'boosting_type': 'Plain', 'model_shrink_mode': 'Constant', 'feature_border_type': 'GreedyLogSum', 'bayesian_matrix_reg': 0.10000000149011612, 'force_unit_auto_pair_weights': False, 'l2_leaf_reg': 3, 'random_strength': 1, 'rsm': 1, 'boost_from_average': False, 'model_size_reg': 0.5, 'pool_metainfo_options': {'tags': {}}, 'subsample': 0.800000011920929, 'use_best_model': False, 'class_names': [0, 1], 'random_seed': 0, 'depth': 4, 'posterior_sampling': False, 'border_count': 254, 'classes_count': 0, 'auto_class_weights': 'None', 'sparse_features_conflict_fraction': 0, 'leaf_estimation_backtracking': 'AnyImprovement', 'best_model_min_trees': 1, 'model_shrink_rate': 0, 'min_data_in_leaf': 1, 'loss_function': 'Logloss', 'learning_rate': 0.01746400073170662, 'score_function': 'Cosine', 'task_type': 'CPU', 'leaf_estimation_iterations': 10, 'bootstrap_type': 'MVS', 'max_leaves': 16}

# 5. Generate predictions on selected model

In [39]:
##Refit model to train on entire dataset
smoter = SMOTE(random_state=0)

X_upsample, y_upsample = smoter.fit_resample(X,y)

rf_model = RandomForestClassifier(n_estimators=100, max_depth=4,random_state=0, max_features="log2")
cat_model = CatBoostClassifier(random_seed = 0, depth = 4,verbose=False) #default depth =6
xgb_model = xgb.XGBClassifier(random_state=0, max_depth=4)

rf_model.fit(X_train_upsample, y_train_upsample)
cat_model.fit(X_train_upsample, y_train_upsample)
xgb_model.fit(X_train_upsample, y_train_upsample)

y_pred1 = rf_model.predict(X_test)
y_pred2 = cat_model.predict(X_test)
y_pred3 = xgb_model.predict(X_test)

[16:49:34] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [40]:
##Selected feature columns for predictions
X_kaggle = test_set[feature_cols]
X_kaggle

,bid_id,auction,merchandise,device,time,country,ip,url,max_bids_auc,avg_bids_auc,...,avg_bids_ip,max_bids_url,avg_bids_url,maxtime,mintime,maxtimediff,meantimediff,mediantimediff,duration,bids_per_auction
0,4.0,3.0,1.0,2.0,4.0,3.0,4.0,3.0,2.0,1.333333,...,1.000000,2.0,1.333333,9.703350e+15,9.633127e+15,5.989721e+13,1.755592e+13,5.163237e+12,7.022368e+13,1.333333
1,3.0,2.0,1.0,3.0,3.0,2.0,2.0,1.0,2.0,1.500000,...,1.500000,3.0,3.000000,9.708415e+15,9.632413e+15,7.600195e+13,2.533402e+13,1.052632e+08,7.600205e+13,1.500000
2,17.0,14.0,1.0,4.0,17.0,3.0,4.0,2.0,2.0,1.214286,...,4.250000,13.0,8.500000,9.705395e+15,9.705104e+15,2.485789e+11,1.712074e+10,2.157895e+09,2.910526e+11,1.214286
3,148.0,90.0,1.0,81.0,148.0,14.0,129.0,80.0,15.0,1.644444,...,1.147287,65.0,1.850000,9.708478e+15,9.631956e+15,5.015947e+13,5.170381e+11,1.019737e+11,7.652163e+13,1.644444
4,23.0,20.0,1.0,17.0,23.0,2.0,17.0,1.0,2.0,1.150000,...,1.352941,23.0,23.000000,9.642466e+15,9.635891e+15,3.373105e+12,2.858604e+11,8.000000e+09,6.574789e+12,1.150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4695,983.0,41.0,1.0,9.0,466.0,5.0,22.0,4.0,86.0,23.975610,...,44.681818,734.0,245.750000,9.703550e+15,9.636261e+15,5.114521e+13,6.845291e+10,0.000000e+00,6.728921e+13,23.975610
4696,66.0,32.0,1.0,29.0,66.0,10.0,49.0,18.0,16.0,2.062500,...,1.346939,32.0,3.666667,9.772885e+15,9.759498e+15,1.570158e+12,2.028373e+11,9.547368e+10,1.338726e+13,2.062500
4697,2162.0,419.0,1.0,376.0,2156.0,86.0,1460.0,1049.0,115.0,5.159905,...,1.480822,725.0,2.061010,9.709201e+15,9.631917e+15,5.006800e+13,3.574636e+10,6.526316e+09,7.728363e+13,5.159905
4698,5.0,5.0,1.0,4.0,5.0,1.0,5.0,2.0,1.0,1.000000,...,1.000000,3.0,2.500000,9.642512e+15,9.633372e+15,5.641158e+12,1.828063e+12,9.474211e+11,9.140316e+12,1.000000
4699,382.0,116.0,1.0,117.0,382.0,10.0,347.0,246.0,15.0,3.293103,...,1.100865,74.0,1.552846,9.709052e+15,9.632008e+15,5.011416e+13,2.016866e+11,3.502632e+10,7.704426e+13,3.293103

In [41]:
#Generate predictions on the test dataset
y_pred1 = rf_model.predict_proba(X_kaggle)
y_pred2 = cat_model.predict_proba(X_kaggle)
y_pred3 = xgb_model.predict_proba(X_kaggle)

probabilities = (y_pred1 * 0.6) + (y_pred2 * 0.3) + (y_pred3 * 0.1)

probabilities

array([[0.99283727, 0.00716273],
       [0.98297029, 0.01702971],
       [0.50975213, 0.49024787],
       ...,
       [0.69819897, 0.30180103],
       [0.99526018, 0.00473982],
       [0.92900157, 0.07099843]])

In [42]:
##Save the prediction outcome of bidder being a bot into an array
kaggle_preds = probabilities[:,1]
kaggle_preds

array([0.00716273, 0.01702971, 0.49024787, ..., 0.30180103, 0.00473982,
       0.07099843])

In [43]:
##Export predictions to csv file
output_dataframe = pd.DataFrame({
    'bidder_id': test_set['bidder_id'],
    'prediction': kaggle_preds
})
output_dataframe.to_csv('EnsembleModel_final_predictions.csv', index=False)